// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRbcvsHon9ykwZYMLQ1xgr5a9XiGfxT9w',
    appId: '1:33081795743:web:e6e8f011da0807058aeeaa',
    messagingSenderId: '33081795743',
    projectId: 'trabalho-mobille',
    authDomain: 'trabalho-mobille.firebaseapp.com',
    databaseURL: 'https://trabalho-mobille-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-mobille.appspot.com',
    measurementId: 'G-9SV6H5H34W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14bXEgbjIwkPsxa3vgvI9J8NMl3wt2Ow',
    appId: '1:33081795743:android:877860be02c7c7be8aeeaa',
    messagingSenderId: '33081795743',
    projectId: 'trabalho-mobille',
    databaseURL: 'https://trabalho-mobille-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-mobille.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQJhtXegwuxkkaCOGx6Q1trf_V9UGZ1c',
    appId: '1:33081795743:ios:ec824f2ae397ff538aeeaa',
    messagingSenderId: '33081795743',
    projectId: 'trabalho-mobille',
    databaseURL: 'https://trabalho-mobille-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-mobille.appspot.com',
    iosClientId: '33081795743-15s05d3jano610nqggqs1e5n9jvv4e8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoCliente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHQJhtXegwuxkkaCOGx6Q1trf_V9UGZ1c',
    appId: '1:33081795743:ios:ec824f2ae397ff538aeeaa',
    messagingSenderId: '33081795743',
    projectId: 'trabalho-mobille',
    databaseURL: 'https://trabalho-mobille-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-mobille.appspot.com',
    iosClientId: '33081795743-15s05d3jano610nqggqs1e5n9jvv4e8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoCliente',
  );
}
